#!/usr/bin/env python3
"""Dump intent-map SQLite DB(s) to Markdown — a plaintext safety net.

The intent DB (docs/*.intent.db) is the canonical documentation store, but it is
a binary SQLite file: a tool bug, a schema migration, or bitrot could make it
unreadable, and git can't diff it. This script renders each DB to a Markdown
sidecar so the intent survives independently of both the binary format and the
intent-map tool.

Resilience by design: it reads the `bindings` table *directly* with Python's
bundled sqlite3 — no dependency on the intent-map binary building or running. If
the tool is what broke, this still works.

The emitted Markdown is one section per binding (label / summary / detail), so a
dump is both human-readable and a re-load source: each entry maps back to
`intent-map allocate --label ... --summary ... --detail ...`.

Usage:
    python scripts/backup_intent_maps.py                 # dump every docs/*.intent.db
    python scripts/backup_intent_maps.py path/to/foo.db  # dump a specific DB
    python scripts/backup_intent_maps.py --check          # verify dumps are current (CI)

By default writes <db>.md next to each <db>. --check re-renders in memory and
diffs against the on-disk .md, exiting nonzero if stale (so CI can gate that the
Markdown mirror was regenerated after a DB change).
"""

import argparse
import glob
import os
import sqlite3
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(REPO, "docs")

# Columns we render, in a stable order. Read directly from the `bindings` table
# (schema: ordinal, label, summary, detail, status, created_at, modified_at,
# retired_at) rather than via the tool's wire grammar.
_SELECT = (
    "SELECT ordinal, label, summary, detail, status, "
    "created_at, modified_at, retired_at "
    "FROM bindings ORDER BY ordinal"
)


def render(db_path):
    """Return the Markdown text for one intent DB."""
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    try:
        rows = list(con.execute(_SELECT))
    finally:
        con.close()

    name = os.path.basename(db_path)
    out = []
    out.append("# intent-map dump — `%s`" % name)
    out.append("")
    out.append(
        "Plaintext mirror of the intent DB, generated by "
        "`scripts/backup_intent_maps.py`. **Do not edit by hand** — edit the DB via "
        "the `intent-map` tool and re-run the dump. Each entry re-loads with "
        "`intent-map allocate --label <label> --summary <summary> --detail <detail>`."
    )
    out.append("")
    out.append("%d binding(s)." % len(rows))
    out.append("")

    for r in rows:
        # A retired (tombstoned) key is still shown — the point of the backup is
        # to lose nothing — but flagged so its status is unambiguous.
        flag = "" if r["status"] == "active" else "  _(retired %s)_" % (r["retired_at"] or "")
        out.append("---")
        out.append("")
        out.append("## `%s`%s" % (r["label"], flag))
        out.append("")
        out.append("**summary:** %s" % r["summary"])
        out.append("")
        detail = r["detail"] or ""
        if detail.strip():
            out.append("**detail:**")
            out.append("")
            # Preserve the author's newlines verbatim inside a fenced block so
            # arrows/section-signs/tabs survive round-trips untouched by Markdown.
            out.append("```text")
            out.append(detail.rstrip("\n"))
            out.append("```")
            out.append("")
        out.append(
            "<sub>ordinal %s · created %s · modified %s · status %s</sub>"
            % (r["ordinal"], r["created_at"], r["modified_at"], r["status"])
        )
        out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def db_targets(argv_paths):
    if argv_paths:
        return [os.path.abspath(p) for p in argv_paths]
    # Default: every tracked intent DB under docs/.
    return sorted(glob.glob(os.path.join(DOCS, "*.intent.db")))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("dbs", nargs="*", help="DB path(s); default: docs/*.intent.db")
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify each <db>.md matches a fresh render; exit 1 if any is stale",
    )
    args = ap.parse_args()

    targets = db_targets(args.dbs)
    if not targets:
        print("no intent DBs found (looked for docs/*.intent.db)", file=sys.stderr)
        return 0  # nothing to do is not an error

    stale = []
    for db in targets:
        if not os.path.exists(db):
            print("error: no such DB: %s" % db, file=sys.stderr)
            return 2
        md_path = db + ".md"
        text = render(db)
        if args.check:
            current = ""
            if os.path.exists(md_path):
                with open(md_path, "r", encoding="utf-8", newline="") as fh:
                    current = fh.read()
            if current != text:
                stale.append(md_path)
                print("STALE: %s" % os.path.relpath(md_path, REPO), file=sys.stderr)
            else:
                print("ok:    %s" % os.path.relpath(md_path, REPO))
        else:
            with open(md_path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            print("wrote  %s" % os.path.relpath(md_path, REPO))

    if args.check and stale:
        print(
            "\n%d dump(s) out of date — run: python scripts/backup_intent_maps.py"
            % len(stale),
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
